- hosts: master
  become: true
  become_method: sudo
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: ~/
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: ~/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: ~/
        creates: pod_network_setup.txt

    - name: install helm
      become: yes
      shell: snap install helm --classic
      
    - name: copy tiller config
      become: yes
      become_user: ubuntu
      copy:
        src: /tmp/ansible/tiller_rbac.yaml
        dest: /tmp/tiller_rbac.yaml
        owner: ubuntu
        mode: '0644'

    - name: create tiller service user
      become: yes
      become_user: ubuntu
      shell: kubectl create -f /tmp/tiller_rbac.yaml

    - name: init tiller
      become_user: ubuntu
      shell: "/snap/bin/helm init --service-account tiller --history-max 150"
